title: Niels's Communications site
description: Niels' Communications
theme: just-the-docs

url: https://nielswritescode.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
